django_easynut/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^nut/', include('emr.urls')),
    url(r'^builder/', include('builder.urls')),
    url(r'^admin/', admin.site.urls),
]

emr/urls.py
# -*- coding: utf-8 -*-
# from django.conf.urls import include
from django.conf.urls import url

# from RESTViews import RecordList, RecordDetail
from . import views


app_name = 'emr'

urlpatterns = [
    url(r'^login/$', views.loginview, name='login'),
    url(r'^logoutbutton/$', views.logoutbutton, name='logoutbutton'),
    # url(r'^api/(?P<table_id>[0-9]+)/$', RecordList.as_view()),
    # url(r'^api/(?P<table_id>[0-9]+)/(?P<pk>(NULL|[0-9]+))/$', RecordDetail.as_view()),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^$', views.index, name='index'),
    url(r'^(?P<record_id>[0-9]+)/patient/$', views.patient, name='patient'),
    url(r'^(?P<table_id>[0-9]+)/(?P<record_id>[0-9]+)/detail/$', views.detail, name='detail'),
    url(r'^(?P<table_id>[0-9]+)/(?P<record_id>[0-9]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<table_id>[0-9]+)/(?P<record_id>[0-9]+)/deleterecord/$', views.deleterecord, name='deleterecord'),
    url(r'^(?P<table_id>[0-9]+)/(?P<record_id>[0-9]+)/print/$', views.export_excel_detail, name='print'),
    url(
        r'^(?P<table_id>[0-9]+)/(?P<related_record_entry>(NULL|[0-9]+))/addrecord/$',
        views.addrecord,
        name='addrecord',
    ),
    url(r'^results/$', views.results, name='results'),
    url(r'^save/$', views.save, name='save'),
    url(r'^downloadexport/$', views.downloadexport, name='downloadexport'),
    url(r'^downloadbackup/$', views.downloadbackup, name='downloadbackup'),
    url(r'^downloadabsents/$', views.downloadabsents, name='downloadabsents'),
    url(r'^downloaddefaulters/$', views.downloaddefaulters, name='downloaddefaulters'),

    url(r'^export/download/(?P<filename>.*)/$', views.export_download_file, name='export_download_file'),
    url(
        r'^export/ajax/is-file-ready/(?P<filename>.*)/$',
        views.export_ajax_is_file_ready,
        name='export_ajax_is_file_ready',
    ),
    url(r'^export/data-model/$', views.export_data_model, name='export_data_model'),
    url(r'^export/excel/full/$', views.export_excel_full, name='export_excel_full'),
    url(r'^export/excel/list/$', views.export_excel_list, name='export_excel_list'),

    url(r'^debug/export/excel/list/$', views.test_export_excel_detail, name='test_export_excel_list'),
    url(
        r'^debug/(?P<table_id>[0-9]+)/(?P<record_id>[0-9]+)/print/$',
        views.test_export_excel_detail,
        name='test_export_excel_detail',
    ),
]

urls.py
# -*- coding: utf-8 -*-
# from django.conf.urls import include
from django.conf.urls import url

# from RESTViews import RecordList, RecordDetail
from . import views


app_name = 'emr'

urlpatterns = [
    url(r'^login/$', views.loginview, name='login'),
    url(r'^logoutbutton/$', views.logoutbutton, name='logoutbutton'),
    # url(r'^api/(?P<table_id>[0-9]+)/$', RecordList.as_view()),
    # url(r'^api/(?P<table_id>[0-9]+)/(?P<pk>(NULL|[0-9]+))/$', RecordDetail.as_view()),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^$', views.index, name='index'),
    url(r'^(?P<record_id>[0-9]+)/patient/$', views.patient, name='patient'),
    url(r'^(?P<table_id>[0-9]+)/(?P<record_id>[0-9]+)/detail/$', views.detail, name='detail'),
    url(r'^(?P<table_id>[0-9]+)/(?P<record_id>[0-9]+)/edit/$', views.edit, name='edit'),
    url(
        r'^(?P<table_id>[0-9]+)/(?P<related_record_entry>(NULL|[0-9]+))/addrecord/$',
        views.addrecord,
        name='addrecord',
    ),
    url(r'^results/$', views.results, name='results'),
    url(r'^save/$', views.save, name='save'),
    url(r'^(?P<table_id>[0-9]+)/(?P<record_id>[0-9]+)/deleterecord/$', views.deleterecord, name='deleterecord'),
    url(r'^downloadexport/$', views.downloadexport, name='downloadexport'),
    url(r'^downloadbackup/$', views.downloadbackup, name='downloadbackup'),
    url(r'^downloadabsents/$', views.downloadabsents, name='downloadabsents'),
    url(r'^downloaddefaulters/$', views.downloaddefaulters, name='downloaddefaulters'),
]

emr/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import os

from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.signals import user_logged_in
from django.core.cache import cache
from django.dispatch import receiver
from django.http import HttpResponseRedirect, HttpResponse, Http404, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.utils.timezone import now


from graphos.renderers import flot
from graphos.sources.simple import SimpleDataSource

from .DAO import DAO
from .exports import AbstractExportExcel, ExportDataModel, ExportExcelFull, ExportExcelList, ExportExcelDetail
from .ExternalExport import ExternalExport
from .models import DynamicRegistry
from .utils import xlsx_download_response_factory


def is_admin_or_redirect(request):
    # User must be in group "Admin".
    if not request.user.groups.filter(id=2).exists():
        return index(request)


# Display log in page
def loginview(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/nut/')
            else:
                return render(request, 'emr/login.html', {
                    'wrongcrendentials': 'Your account is disabled.'
                })
        else:
            return render(request, 'emr/login.html', {
                'wrongcrendentials': 'Invalid username / password combination provided'
            })
    else:
        return render(request, 'emr/login.html', {'wrongcrendentials': ''})


# Log out
def logoutbutton(request):
    logout(request)
    return render(request, 'emr/login.html', {'wrongcrendentials': ''})


# Home page
@login_required
def index(request):
    template_name = 'emr/index.html'
    daoobject = DAO()
    daoobject = getTableConfigandUser(request, daoobject)
    # *TBC*#
    # Last ID not used anymore
    return render(request, template_name, {
        'edbtables': daoobject.tables_config_lite,
        'lastId': daoobject.getLastId('tabla_1', 'campo_1'),
        'easyUser': daoobject.easy_user,
    })


# Display search results
@login_required
def results(request):
    template_name = 'emr/results.html'
    search_query = request.GET.get('searchstring')
    daoobject = DAO()
    daoobject = getTableConfigandUser(request, daoobject)
    regularsearch = render(request, template_name, {
        'searchresults': daoobject.search(search_query, '1'),
        'lastId': daoobject.getLastId('tabla_1', 'campo_1'),
        'easyUser': daoobject.easy_user,
    })
    try:
        searchInt = int(search_query)
        searchStr = str(searchInt)
        zerosToAdd = 6-len(searchStr)
        IdToReturn = ''
        for i in xrange(zerosToAdd):
            IdToReturn = IdToReturn + '0'
        if daoobject.doesIdExist(IdToReturn + searchStr):
            return patient(request, daoobject.doesIdExist(IdToReturn + searchStr))
        else:
            return regularsearch
    except ValueError:
        return regularsearch


# Display patient summary
@login_required
def patient(request, record_id):
    template_name = 'emr/patient.html'
    daoobject = DAO()
    daoobject = getTableConfigandUser(request, daoobject)
    daoobject.set_graphs(record_id)
    # Initialise graphos chart objects
    charts = []
    for graph in daoobject.graphs:
        charts.append([
            graph[0],
            flot.LineChart(
                SimpleDataSource(data=graph[3]),
                options={
                    'title': graph[2] + ' / ' + graph[1],
                    'xaxis': {'mode': "time", 'timezone': 'browser'},
                    'bars': {'barWidth': 86400000},
                    'legend': {'show': False, 'position': 'sw'},
                    'grid': {
                        'borderWidth': {'top': 0, 'right': 0, 'bottom': 2, 'left': 2},
                        'borderColor': {'bottom': "#999", 'left': "#999"},
                        'hoverable': True
                    },
                    'tooltip': {'show': True, 'content': '%x: %y'},
                }
            )
        ])
    daoobject.get_record_with_type('1', record_id, True)
    daoobject.get_related_records(record_id)
    daoobject.getLastId('tabla_1', 'campo_1')

    return render(request, template_name, {
        'record': daoobject.get_record_with_type('1', record_id, True),
        'relatedrecords': daoobject.get_related_records(record_id),
        'charts': charts,
        'graphs': daoobject.graphs,
        'lastId': daoobject.getLastId('tabla_1', 'campo_1'),
        'easyUser': daoobject.easy_user,
    })


# View a specific record
@login_required
def detail(request, table_id, record_id):
    template_name = 'emr/detail.html'
    daoobject = DAO()
    daoobject = getTableConfigandUser(request, daoobject)
    if daoobject.backEndUserRolesCheck(table_id, 'view_table'):
        return render(request, template_name, {
            'record': daoobject.get_record_with_type(table_id, record_id, False),
            'lastId': daoobject.getLastId('tabla_1', 'campo_1'),
            'easyUser': daoobject.easy_user,
        })
    return index(request)


# Edit a record
@login_required
def edit(request, table_id, record_id):
    template_name = 'emr/edit.html'
    daoobject = DAO()
    daoobject = getTableConfigandUser(request, daoobject)
    if daoobject.backEndUserRolesCheck(table_id, 'edit_table'):
        return render(request, template_name, {
            'record': daoobject.get_record_with_type(table_id, record_id, False),
            'lastId': daoobject.getLastId('tabla_1', 'campo_1'),
            'easyUser': daoobject.easy_user,
        })
    return index(request)


# Save a record
@login_required
def save(request):
    record_id = request.POST.get('record_id')
    table_id = request.POST.get('table_id')
    daoobject = DAO()
    daoobject = getTableConfigandUser(request, daoobject)
    fieldstochange = []
    patientId = 0
    # *TBC*#
    # Lost of nested loops
    for tablec in daoobject.tables_config:
        if tablec['id'] == table_id:
            for fieldc in tablec['fields']:
                if fieldc['name'] == 'MSF ID':
                    patientId = daoobject.getPatientIdFromMsfId(request.POST.get(fieldc['field']))
                fieldstochange.append([fieldc['field'], request.POST.get(fieldc['field']), fieldc['type']])
            fieldstochange.append(['user', request.user.username, '2'])
    if record_id != "0":
        if daoobject.backEndUserRolesCheck(table_id, 'edit_table'):
            daoobject.editrecord(table_id, record_id, fieldstochange)
    else:
        if daoobject.backEndUserRolesCheck(table_id, 'add_table'):
            record_id = daoobject.insertrecord(table_id, fieldstochange)
            if table_id == '1':
                patientId = record_id
    return HttpResponseRedirect(reverse('emr:patient', args=(patientId,)))


# Add a new record
@login_required
def addrecord(request, table_id, related_record_entry):
    template_name = 'emr/addrecord.html'
    daoobject = DAO()
    daoobject = getTableConfigandUser(request, daoobject)
    if daoobject.backEndUserRolesCheck(table_id, 'add_table'):
        if (related_record_entry == '0') and (table_id == '1'):
            related_record_field = 'campo_1'
        else:
            related_record_field = 'campo_2'
        if table_id != "0":
            return render(request, template_name, {
                'recordform': daoobject.getrecordform(table_id),
                'related_record_entry': related_record_entry,
                'related_record_field': related_record_field,
                'lastId': daoobject.getLastId('tabla_1', 'campo_1'),
                'easyUser': daoobject.easy_user,
            })
    return index(request)


# Delete a record
@login_required
def deleterecord(request, table_id, record_id):
    daoobject = DAO()
    daoobject = getTableConfigandUser(request, daoobject)
    if daoobject.backEndUserRolesCheck(table_id, 'delete_table'):
        daoobject.delete(table_id, record_id)
    return index(request)


# Download raw export
@login_required
def downloadexport(request):
    is_admin_or_redirect(request)

    daoobject = DAO()
    daoobject = getTableConfigandUser(request, daoobject)
    # If user is in group "Admin"
    if request.user.groups.filter(id=2).exists():
        zip = daoobject.generateExport()+'.zip'
        if os.path.exists(zip):
            with open(zip, 'rb') as fh:
                response = HttpResponse(fh.read(), content_type="application/zip")
                response['Content-Disposition'] = 'inline; filename=' + os.path.basename(zip)
                return response
        raise Http404
    else:
        return index(request)


# Download single-file export
@login_required
def downloadsfexport(request):
    is_admin_or_redirect(request)

    daoobject = DAO()
    daoobject = getTableConfigandUser(request, daoobject)
    if request.user.groups.filter(id=2).exists():
        zip = daoobject.generateSingleFileExport()+'.zip'
        if os.path.exists(zip):
            with open(zip, 'rb') as fh:
                response = HttpResponse(fh.read(), content_type="application/zip")
                response['Content-Disposition'] = 'inline; filename=' + os.path.basename(zip)
                return response
        raise Http404
    else:
        return index(request)


# Download backup
@login_required
def downloadbackup(request):
    is_admin_or_redirect(request)

    daoobject = DAO()
    daoobject = getTableConfigandUser(request, daoobject)
    if request.user.groups.filter(id=2).exists():
        file = u'/opt/shared/backup.gz.enc'
        if os.path.exists(file):

templates/emr/baseOld.html
{% load staticfiles %}

<html>

	<link rel="stylesheet" type="text/css" href="{% static 'emr/style.css' %}" />
	<script type="text/javascript" src="/static/emr/js/jquery-3.2.1.min.js"></script> 
	<link rel="stylesheet" type="text/css" href="{% static 'emr/jquery-ui.css' %}" />
	<script type="text/javascript" src="/static/emr/js/jquery-ui.js"></script>	
	<script type="text/javascript">
		$(document).ready( function() {
			$("#nextId").click(function () {
				alert("Last ID used: {{ lastId }}");
			});
		});
	</script>

	<head>
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <title>Fori - EasyNut</title>
	</head>
	
	<header>
		<div class='elementclass'>
			<div class="background-image"></div>
			<h1>EasyNut</h1>
			<h3>Fori - Nutrition System</h3>		
		</div>
		<div class='elementclass'>
			<nav class="rightalign">
				<li><a href="{% url 'emr:index' %}" class="btn">Home</a></li>
			</nav class="rightalign">
			<nav>
				<li><a href="#" accesskey="1" id="nextId" class="btn">Last ID</a></li>
				<li><a href="{% url 'emr:downloadexport' %}" accesskey="2" class="btn">Export</a></li>
			</nav>
		</div>
	</header>
	
	<body>	
		
		<section class="features">
            {% block content %}
            {% endblock %}		
		</section>	
			
		<footer>
			<p>MSF - Nigeria - Fori | Support: <a href="mailto:msfocb-blantyre-ehealth@brussels.msf.org">msfocb-blantyre-ehealth@brussels.msf.org</a> | OCB eHealth</a>.</p>
		</footer>		
	</body>
</html>

templates/emr/index.html
{% extends "emr/base.html" %}

{% block content %}
	<section class="hero is-fullheight">
		<br/>
		<div align="center" class="specialAndroid"><br/>
			<a href="zxing://scan/?ret=http%3A%2F%2F192.168.8.102/nut/results/?searchstring=%7BCODE%7D&search=SEARCH" class="button is-doudou go">Scan</a>
			<h1 class="title has-text-centered is-doudou">or</h1>	
		</div>
		<br/>
		<div align="center"><br/>
			<form action="{% url 'emr:results' %}" type="get">
				<table>
					<tr><input type="text" id="searchstring" placeholder="Access by ID or search patients" name="searchstring" class="searchbox"/></tr>
					<tr>&nbsp;</tr>
					<tr><b>&</b></tr>
					<tr>&nbsp;</tr>
					<tr><input type="submit" name="search" value="SEARCH" class="searchnow"/></tr>
				</table>			
			</form>
		</div>
		{% if easyUser.tables.1.add_table %}
			<h1 class="title has-text-centered is-doudou">or</h1>	
			<div align="center">
				{% with table_id='1' related_record_entry='0' %}
					<a href="{% url 'emr:addrecord' table_id related_record_entry %}" class="button is-doudou go">Add patient</a>
				{% endwith %}		
			</div>
			<p></p>
		{% else %}
			<p></p>
			<p></p>
			<p></p>
			<p></p>
		{% endif %}
		
		{% if easyUser.canExport %}
			<div align="center"><br/><br/>
				<h1 class="title has-text-centered is-doudou">Data:</h1>
				<a href="{% url 'emr:downloadabsents' %}" accesskey="2" class="button is-doudou go">Get absents ( > 7 and < 14 days)</a><br/>
				<a href="{% url 'emr:downloaddefaulters' %}" accesskey="2" class="button is-doudou go">Get unregistred defaulters ( > 14 days)</a><br/>						
				<a href="{% url 'emr:downloadexport' %}" accesskey="2" class="button is-doudou go">Export all</a><br/>
				<a href="{% url 'emr:downloadbackup' %}" accesskey="2" class="button is-doudou go">Download backup</a><br/>
			</div>
		{% endif %}
		
	</section>
{% endblock %}

templates/emr/login.html
{% extends "emr/base.html" %}

{% block content %}	
	<section class="hero is-fullheight">
		<div align="center">
			<br/>
			{% if wrongcrendentials %}
				<span  style="color:red; font-weight: bold;">{{ wrongcrendentials }}</span>
				<p><br/></p>
			{% endif %}
			<form id="login_form" method="POST" action="{% url 'emr:login' %}">
				<table>
					{% csrf_token %}
					<tr><input class="searchbox" type="text" name="username" value="" placeholder="Username"/></tr>
					<tr>&nbsp;</tr>
					<tr><input class="searchbox" type="password" name="password" value="" placeholder="Password"/></tr>
					<tr>&nbsp;</tr>
					<tr><input class="searchnow" type="submit" value="Login"  class="has-text-centered"/></tr>
				</table>
			</form>
		</div>
	</section>
{% endblock %}

templates/emr/patient.html
{% extends "emr/base.html" %}

{% block content %}	
	<section class="hero is-light">
		<div class="hero-body">
			<br/>
			<div class="container">
				{% with record_id=record.1 table_id=record.0 %}	
					<table>
						<tr>
							<td><span class="title">Patient #{{ record.3.0.4 }}</span></td>
							{% if easyUser.tables.1.view_table %}<td width="5%"><a href="{% url 'emr:detail' table_id record_id %}" class="button is-mei go">View</a></td>{% endif %}
							{% if easyUser.tables.1.edit_table %}<td width="5%"><a href="{% url 'emr:edit' table_id record_id %}" class="button is-mei careful">Edit</a></td>{% endif %}
							{% if easyUser.tables.1.delete_table %}<td width="5%"><a href="{% url 'emr:deleterecord' table_id record_id %}" class="button is-mei dangerous" onclick="return confirm('Are you sure you want to delete this patient?')">Delete</a></td>{% endif %}				
						</tr>
					</table>
				{% endwith %}
			</div>
			<div class="container">			
				<br/>				
				<table class="table">
					{% for field in record.3 %}
						<tr>
							<td><b>{% if field.3 == None %}Not recorded{% else %}{{ field.3 }}{% endif %}</b></td>
							<td>{% if field.4 == None %}Not recorded{% else %}{{ field.4 }}{% endif %}</td>
						</tr>
					{% endfor %}
				</table>
			</div>
			{% if relatedrecords %}
				<br/>
				{% for relatedrecord in relatedrecords %}
					{% for tableresults in relatedrecord.1 %}				
						{% with table_id=tableresults.1 table_id2=tableresults.1 related_record_entry=relatedrecord.0.0 %}
							<div class="container">
								<table>
									<tr>
										<td><span class="subtitle">{{ tableresults.0 }}</span></td>
										{% for k,v in easyUser.tables.items %}
											{% if k == table_id and v.add_table %}
												<td width='5%'>
													<a href="{% url 'emr:addrecord' table_id related_record_entry %}" class="button is-mei go">
														Add
													</a>
												</td>
											{% endif %}
										{% endfor %}
									</tr>
								</table>
							</div>
						{% endwith %}
						<div class="container">
							<div class="columns">
								<div class="column is-12 scroll">
									<table id="nofeatures" class="table is-striped is-bordered" cellspacing="0" width="100%">
								        <thead>
								            <tr>
								          		{% for k,v in easyUser.tables.items %}
													{% if k == tableresults.1 and v.view_table %}
														<th  scope="col" width="5%">View</td>
													{% endif %}
												{% endfor %}														
												{% for columnname in tableresults.2 %}
													<th scope="col">{{ columnname }}</td>
												{% endfor %}
								          		{% for k,v in easyUser.tables.items %}
													{% if k == tableresults.1 and v.edit_table %}
														<th  scope="col" width="5%">Edit</td>
													{% endif %}
												{% endfor %}														
								          		{% for k,v in easyUser.tables.items %}
													{% if k == tableresults.1 and v.delete_table %}
														<th  scope="col" width="5%">Delete</td>
													{% endif %}
												{% endfor %}														
											</tr>
										</thead>
										<tbody>
											{% if not tableresults.3 %}
												<tr>
													<td colspan="{{ tableresults.2|length|add:'+3' }}">No related records found</td>
												</tr>
											{% else %}
												{% for records in tableresults.3 %}
													<tr>
														{% with record_id=records.0 table_id=tableresults.1 %}
											          		{% for k,v in easyUser.tables.items %}
																{% if k == tableresults.1 and v.view_table %}
																	<td width="5%"><a href="{% url 'emr:detail' table_id record_id %}" class="button is-mei go">View</a></td>													
																{% endif %}
															{% endfor %}																												
														{% endwith %}
														{% for record in records %}
															{% if forloop.counter != 1 %}
																{% with record_id=records.0 table_id=tableresults.1 %}
																	<td>{% if record == None %}Not recorded{% else %}{{ record }}{% endif %}</td>
																{% endwith %}
															{% endif %}
														{% endfor %}
														{% with record_id=records.0 table_id=tableresults.1 %}
											          		{% for k,v in easyUser.tables.items %}
																{% if k == tableresults.1 and v.edit_table %}														
																	<td width="5%"><a href="{% url 'emr:edit' table_id record_id %}" class="button is-mei careful">Edit</a></td>
																{% endif %}
															{% endfor %}																												
											          		{% for k,v in easyUser.tables.items %}
																{% if k == tableresults.1 and v.delete_table %}																
																	<td width="5%"><a href="{% url 'emr:deleterecord' table_id record_id %}" class='button is-mei dangerous' onclick="return confirm('Are you sure you want to delete this record?')">Delete</a></td>
																{% endif %}
															{% endfor %}																												
														{% endwith %}
													</tr>
												{% endfor %}
												{% for chart in charts %}
													{% if chart.0 == tableresults.1 %} 
													<tr>
														<td colspan="{{ tableresults.2|length|add:'+3' }}">
														<center><br/>
														<strong>{{ chart.1.options.title }} diagram</strong>
														<br/>
														{{ chart.1.as_html }}</center>
														</td>
													</tr>
													{% endif %}
												{% endfor %}
											{% endif %}
										</tbody>
									</table>
								</div>
							</div>
						</div>
					{% endfor %}	
					<p><br/></p>	
				{% endfor %}				
			{% endif %}
		</div>
		<br/>
	</section>
{% endblock %}

templates/emr/results.html
{% extends "emr/base.html" %}

{% block content %}	
	<section class="hero doudoucolor">
		<div align="center">
			<br/>
			<form action="{% url 'emr:results' %}" type="get">
				<table>
					<tr><input type="text" id="searchstring" placeholder="Access by ID or search patients" name="searchstring" class="searchbox"/></tr>
					<tr>&nbsp;</tr>
					<tr><b>&</b></tr>
					<tr>&nbsp;</tr>
					<tr><input type="submit" name="search" value="SEARCH" class="searchnow"/></tr>
				</table>			
			</form>
		</div>	
	</section>
	<section class="hero is-light">
		<div class="hero-body">
			<br/>
			<div class="container">
				<h1 class="title">
	                Patient(s) matching "{{ searchresults.0.0 }}":
              	</h1>
			</div>
		</div>
		<div class="container">
			<div class="columns">
				{% for tableresults in searchresults.1 %}
					<div class="column is-12 scroll">
						<table id="nofeatures" class="table is-striped is-bordered" cellspacing="0" width="100%">
					        <thead>
					            <tr>
									{% for columnname in tableresults.2 %}
										<th scope="col">{{ columnname }}</td>
									{% endfor %}
									{% if easyUser.tables.1.view_table %}<th  scope="col" width="5%">View</td>{% endif %}
									{% if easyUser.tables.1.edit_table %}<th  scope="col" width="5%">Edit</td>{% endif %}
									{% if easyUser.tables.1.delete_table %}<th  scope="col" width="5%">Delete</td>{% endif %}
					            </tr>
					        </thead>				        	
					        <tbody>
								{% if not tableresults.3 %}
									<tr>
										<td colspan="{{ tableresults.2|length|add:'+2' }}">No results found for this search</td>
									</tr>
								{% else %}
									{% for records in tableresults.3 %}
										<tr>
											{% for record in records %}
												{% if forloop.counter == 2 %}
													{% with record_id=records.0 %}
														<td><a href="{% url 'emr:patient' record_id %}" class="button is-mei go">{{ record }}</a></td>
													{% endwith %}
												{% elif forloop.counter != 1 %}
													{% with record_id=records.0 %}
														<td>{% if record == None %}Not recorded{% else %}{{ record }}{% endif %}</td>
													{% endwith %}
												{% endif %}
											{% endfor %}
											{% with record_id=records.0 table_id=tableresults.1 %}
												{% if easyUser.tables.1.view_table %}<td width="5%"><a href="{% url 'emr:detail' table_id record_id %}" class="button is-mei go">View</a></td>{% endif %}
												{% if easyUser.tables.1.edit_table %}<td width="5%"><a href="{% url 'emr:edit' table_id record_id %}" class="button is-mei careful">Edit</a></td>{% endif %}
												{% if easyUser.tables.1.delete_table %}<td width="5%"><a href="{% url 'emr:deleterecord' table_id record_id %}" class="button is-mei dangerous" onclick="return confirm('Are you sure you want to delete this record?')">Delete</a></td>{% endif %}
											{% endwith %}
										</tr>
									{% endfor %}			
								{% endif %}					        
							</tbody>
						</table>
					</div>
				{% endfor %}
			</div>
			<p></p>
			<i>* This version of EasyNut is limited to 100 results per table. If you reached this limit and did not find anything relevant, refine your search</i><p><br/></p>	
		</div>
	</section>
{% endblock %}