emr/urls.py
# -*- coding: utf-8 -*-
# from django.conf.urls import include
from django.conf.urls import url

# from RESTViews import RecordList, RecordDetail
from . import views


app_name = 'emr'

urlpatterns = [
    url(r'^login/$', views.loginview, name='login'),
    url(r'^logoutbutton/$', views.logoutbutton, name='logoutbutton'),
    # url(r'^api/(?P<table_id>[0-9]+)/$', RecordList.as_view()),
    # url(r'^api/(?P<table_id>[0-9]+)/(?P<pk>(NULL|[0-9]+))/$', RecordDetail.as_view()),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^$', views.index, name='index'),
    url(r'^(?P<record_id>[0-9]+)/patient/$', views.patient, name='patient'),
    url(r'^(?P<table_id>[0-9]+)/(?P<record_id>[0-9]+)/detail/$', views.detail, name='detail'),
    url(r'^(?P<table_id>[0-9]+)/(?P<record_id>[0-9]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<table_id>[0-9]+)/(?P<record_id>[0-9]+)/deleterecord/$', views.deleterecord, name='deleterecord'),
    url(r'^(?P<table_id>[0-9]+)/(?P<record_id>[0-9]+)/print/$', views.export_excel_detail, name='print'),
    url(
        r'^(?P<table_id>[0-9]+)/(?P<related_record_entry>(NULL|[0-9]+))/addrecord/$',
        views.addrecord,
        name='addrecord',
    ),
    url(r'^results/$', views.results, name='results'),
    url(r'^save/$', views.save, name='save'),
    url(r'^downloadexport/$', views.downloadexport, name='downloadexport'),
    url(r'^downloadbackup/$', views.downloadbackup, name='downloadbackup'),
    url(r'^downloadabsents/$', views.downloadabsents, name='downloadabsents'),
    url(r'^downloaddefaulters/$', views.downloaddefaulters, name='downloaddefaulters'),

    url(r'^export/download/(?P<filename>.*)/$', views.export_download_file, name='export_download_file'),
    url(
        r'^export/ajax/is-file-ready/(?P<filename>.*)/$',
        views.export_ajax_is_file_ready,
        name='export_ajax_is_file_ready',
    ),
    url(r'^export/data-model/$', views.export_data_model, name='export_data_model'),
    url(r'^export/excel/full/$', views.export_excel_full, name='export_excel_full'),
    url(r'^export/excel/list/$', views.export_excel_list, name='export_excel_list'),

    url(r'^debug/export/excel/list/$', views.test_export_excel_detail, name='test_export_excel_list'),
    url(
        r'^debug/(?P<table_id>[0-9]+)/(?P<record_id>[0-9]+)/print/$',
        views.test_export_excel_detail,
        name='test_export_excel_detail',
    ),
]

emr/templates/emr/addrecord.html
{% extends "emr/base.html" %}
{% block content %}	

	<section class="hero is-light">
		<div class="hero-body">
			<br/>
			<div class="container">
				<table>
					<tr>
						<td><span class="title">Create new {{ recordform.1 }}</span></td>
						<td width="5%"><a href="javascript:history.back()" class="button is-mei careful" onclick="return confirm('The changes made are not going to be saved. Are you sure?')">Back</a></td>
					</tr>
				</table>
				<br/>
				<form action="{% url 'emr:save' %}" method="post">
					{% csrf_token %}
					<input type="hidden" name="record_id" value=0>
					<input type="hidden" name="table_id" value="{{ recordform.0 }}">		
					<div class="columns">
						<div class="column is-12 scroll">
							<table id="nofeatures" class="table is-striped is-bordered" cellspacing="0" width="100%">
								{% for field in recordform.2 %}
									{% if field.3 != 'MSF ID' or recordform.0 != '1' %}
										<tr>
											<td width="30%"><b>{{ field.3 }}</b></td>
											<td>
												{% if field.1 == 0 %}
													<input type="date" class="datepicker-doudou" name="{{ field.0 }}"/>
												{% elif field.1 == 1 %}
													<div class="numbersOnly"><input type="number" step='0.1' name="{{ field.0 }}" {% if field.0 == related_record_field %}value="{{ related_record_entry }}"{% endif %}/> (number only)</div>
												{% elif field.1 == 2 %}
													{% if field.3 == 'MSF ID' %}<div class="numbersOnly">{% endif %} 
														<input type="text" class="input" 
														{% if field.0 == related_record_field %}value="{{ related_record_entry }}"{% endif %} 
														{% if field.3 == 'MSF ID' %} readonly='true'{% endif %}
														name="{{ field.0 }}">
													{% if field.3 == 'MSF ID' %}</div>{% endif %} 
												{% elif field.1 == 3 %}
													<span class="select is-fullwidth">
														<select class="select" name="{{ field.0 }}">
															{% for choice in field.4 %}
																<option value="{{ choice }}">{{ choice }}</option>
															{% endfor %}				
														</select>						
													</span>				
												{% elif field.1 == 5 %}
													<div class="radiosection">
														{% for choice in field.4 %}												
															<input id="{{ field.0 }}{{ choice }}" name="{{ field.0 }}" type="radio" value="{{ choice }}"/>
															<label for="{{ field.0 }}{{ choice }}" class="side-label">{{ choice }}</label>												
														{% endfor %}
													</div>						
												{% elif field.1 == 4 %}
													<div class="textdiv"><textarea  class="textarea" name="{{ field.0 }}"></textarea></div>
												{% endif %}
											</td>									
										</tr>	
									{% endif %}
								{% endfor %}
							</table>
						</div>
					</div>
					
					<table>
						<tr>
							<td><input type="submit" name="Save" value="Save" class="searchnow" onclick="this.disabled=true;this.value='Submitting...';this.form.submit();"/></td>
						</tr>
					</table>					
				</form>
			</div>
		</div>
	</section>
{% endblock %}

emr/templates/emr/base.html
{% load staticfiles %}

<html>

	<head>



		<link rel="icon" type="image/png" sizes="192x192"  href="{% static 'emr/icons/android-icon-192x192.png' %}">
		<link rel="icon" type="image/png" sizes="32x32" href="{% static 'emr/icons/favicon-32x32.png' %}">
		<link rel="icon" type="image/png" sizes="96x96" href="{% static 'emr/icons/favicon-96x96.png' %}">
		<link rel="icon" type="image/png" sizes="16x16" href="{% static 'emr/icons/favicon-16x16.png' %}">
		<link rel="manifest" href="{% static 'emr/icons/manifest.json' %}">
		<meta name="msapplication-TileColor" content="#ffffff">
		<meta name="msapplication-TileImage" content="{% static 'emr/icons/ms-icon-144x144.png' %}">
     	<link rel="shortcut icon" sizes="192x192" href="{% static 'emr/icons/android-icon-192x192.png' %}">
   		<meta name="theme-color" content="#ffffff">
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="mobile-web-app-capable" content="yes">
	    <title>Fori - EasyNut</title>

		<link rel="stylesheet" type="text/css" href="{% static 'emr/style.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'emr/styleDoudou.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'emr/datepicker.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'emr/jquery-ui.css' %}" />

		<script type="text/javascript" src="/static/emr/js/jquery-3.2.1.min.js"></script>
		<script type="text/javascript" src="/static/emr/js/jquery-ui.js"></script>
        <script type="text/javascript" src="/static/emr/js/datepicker.min.js"></script>
        <script type="text/javascript" src="/static/emr/js/i18n/datepicker.en.js"></script>
	<script type="text/javascript" src="/static/emr/js/flot/jquery.flot.js"></script>
	<script type="text/javascript" src="/static/emr/js/flot/jquery.flot.time.js"></script>
	<script type="text/javascript" src="/static/emr/js/flot/jquery.flot.tooltip.js"></script>


	</head>

		<script type="text/javascript">
			$(document).ready( function() {
				$("#lastIdClick").click(function () {
					alert("Last ID used: {{ lastId }}");
				});
				var ua = navigator.userAgent.toLowerCase();
				var isAndroid = ua.indexOf("android") > -1;

				if (!isAndroid){
					$(".datepicker-doudou").datepicker({
						language: 'en',
						dateFormat: 'yyyy-mm-dd',
						todayButton: new Date(),
						autoClose: true
					});
					$(".specialAndroid").hide();
				}
				$('.numbersOnly').children(":first").keyup(function () {
				    this.value = this.value.replace(/[^0-9\.]/g,'');
				});
			});
		</script>

	<body>
		<nav class="nav has-shadow is-fixed-top">
			<div class="container">
				<div class="nav-left">
				  	<a class="nav-item is-brand" href="{% url 'emr:index' %}">Home</a>
	  			</a>
				</div>
				<div class="nav-right">
					<a class="nav-item" href="{% url 'emr:logoutbutton' %}" accesskey="3" class="btn">Log out: {{ user.username }}</a>
				</div>
			</div>
		</nav>
		<div id="main">
			<section class="section">
				<div class="container">
					<div class="heading">
						<a href="{% url 'emr:index' %}"><h1 class="title">EasyNut</h1><h5 class="subtitle">Fori - Nutrition System</h5><h6>Version 1.0</h6></a>
					</div>
				</div>
			</section>
		</div>
		{% block content %}
		{% endblock %}
		<footer class="footer">
        	<div class="container">
            	<div class="content has-text-centered">
            		<p>MSF - Nigeria - Fori<br/>
            		<a href="mailto:msfocb-blantyre-ehealth@brussels.msf.org">msfocb-blantyre-ehealth@brussels.msf.org</a><br/>
            		OCB eHealth</p>
          		</div>
        	</div>
        </footer>
    {% block js %}{% endblock js %}
	</body>
</html>

emr/templates/emr/detail.html
{% extends "emr/base.html" %}

{% block content %}
  <section class="hero is-light">
    <div class="hero-body">
      <br/>
      <div class="container">
        <table>
          <tr>
            <td><span class="title">View {{ record.2 }} record</span></td>
            <td width="5%"><a href="{% url 'emr:patient' record.4 %}" class="button is-mei go">Patient's Summary</a></td>
          </tr>
        </table>
        <br/>
        <div class="columns">
          <div class="column is-12 scroll">
            <table id="nofeatures" class="table is-striped is-bordered" cellspacing="0" width="100%">
              {% for field in record.3 %}
                <tr>
                  <td><b>{{ field.3 }}</b></td>
                  <td>{% if field.4 == None %}Not recorded{% else %}{{ field.4 }}{% endif %}</td>
                </tr>
              {% endfor %}
            </table>
          </div>
        </div>
        {% with record_id=record.1 table_id=record.0 %}
          <br/>
          <table class="tablep">
            <tr>
              <td width='20%' align="left"><a href="{% url 'emr:patient' record.4 %}" class="button is-mei go">Patient</a></td>
              <td width='20%'>&nbsp;</td>
              <td width='20%' align="center"><a href="{% url 'emr:print' table_id record_id %}" class="button is-mei go">Print</a></td>
              {% for k,v in easyUser.tables.items %}
                {% if k == table_id and v.edit_table %}
                  <td width='20%'>&nbsp;</td>
                  <td width='20%' align="center"><a href="{% url 'emr:edit' table_id record_id %}" class="button is-mei careful">Edit</a></td>
                {% endif %}
              {% endfor %}
              {% for k,v in easyUser.tables.items %}
                {% if k == table_id and v.delete_table %}
                  <td width='20%'>&nbsp;</td>
                  <td width='20%' align="right"><a href="{% url 'emr:deleterecord' table_id record_id %}" class="button is-mei dangerous">Delete</a></td>
                {% endif %}
              {% endfor %}
            </tr>
          </table>
        {% endwith %}
      </div>
    </div>
  </section>
  <p></p>
{% endblock content %}

emr/templates/emr/exports.html
{% extends "emr/base.html" %}
{% load staticfiles %}

{% block content %}
  <section class="hero is-light">
    <div class="hero-body">
      <br/>
      <div class="container">
        {% if mode == "background" %}
          <div id="ajax-response">
            Please wait, export in progress. This may take several minutes.<br>
            A download link will appear when the file is ready for download.
          </div>
          <br>
        {% endif %}
        <a id="download-link" href="{% url 'emr:export_download_file' filename %}" class="button is-mei go">Download file</a>
      </div>
    </div>
  </section>
{% endblock content %}

{% block js %}
  {{ block.super }}
  {% if mode == "background" %}
    <script src="{% static 'emr/js/exports.js' %}"></script>
    <script>
      export_ajax_check_file_ready(
        '{% url "emr:export_ajax_is_file_ready" filename %}', 15, 30 * 60,
        function (response) {
          $('#download-link').show();
          $('#ajax-response').html('Your file is ready for download.');
        },
        function (execution_time) {
          $('#download-link').removeAttr('disabled');
          var delay = execution_time;
          var unit = 'seconds';
          if (execution_time > 60) {
            execution_time = execution_time / 60;
            unit = 'minutes';
          }
          $('#ajax-response').html(
            '<p>The export is still running but we stopped checking after ' + execution_time + ' ' + unit + '.</p>' +
            '<p><strong>DO NOT RELOAD THIS PAGE</strong> as it would generate a new export that will also take more time.</p>' +
            '<p>Please keep this page open and try in a few minutes to click the download button here below.</p>' +
            '<p>If it returns an error, it should be normal. As it will open in a new tab or window, you can close that one and try again later on this page.</p>'
          );
          $('#download-link').attr('target', '_blank').show();
        }
      );
      $(function () {
        $('#download-link').hide();
      });
    </script>
  {% endif %}
{% endblock js %}

emr/templates/emr/index.html
{% extends "emr/base.html" %}

{% block content %}
	<section class="hero is-fullheight">
		<br/>
		<div align="center" class="specialAndroid"><br/>
			<a href="zxing://scan/?ret=http%3A%2F%2F192.168.8.102/nut/results/?searchstring=%7BCODE%7D&search=SEARCH" class="button is-doudou go">Scan</a>
			<h1 class="title has-text-centered is-doudou">or</h1>
		</div>
		<br/>
		<div align="center"><br/>
			<form action="{% url 'emr:results' %}" type="get">
				<table>
					<tr><input type="text" id="searchstring" placeholder="Access by ID or search patients" name="searchstring" class="searchbox"/></tr>
					<tr>&nbsp;</tr>
					<tr><b>&</b></tr>
					<tr>&nbsp;</tr>
					<tr><input type="submit" name="search" value="SEARCH" class="searchnow"/></tr>
				</table>
			</form>
		</div>
		{% if easyUser.tables.1.add_table %}
			<h1 class="title has-text-centered is-doudou">or</h1>
			<div align="center">
				{% with table_id='1' related_record_entry='0' %}
					<a href="{% url 'emr:addrecord' table_id related_record_entry %}" class="button is-doudou go">Add patient</a>
				{% endwith %}
			</div>
			<p></p>
		{% else %}
			<p></p>
			<p></p>
			<p></p>
			<p></p>
		{% endif %}

		{% if easyUser.canExport %}
			<div align="center"><br/><br/>
				<h1 class="title has-text-centered is-doudou">Data:</h1>
				<a href="{% url 'emr:downloadabsents' %}" accesskey="2" class="button is-doudou go">Get absents ( > 7 and < 14 days)</a><br/>
				<a href="{% url 'emr:downloaddefaulters' %}" accesskey="2" class="button is-doudou go">Get unregistred defaulters ( > 14 days)</a><br/>
				<a href="{% url 'emr:downloadexport' %}" accesskey="2" class="button is-doudou go">Export all</a><br/>
				<a href="{% url 'emr:downloadbackup' %}" accesskey="2" class="button is-doudou go">Download backup</a><br/>
        <br/>
        <a href="{% url 'emr:export_excel_list' %}" accesskey="2" class="button is-doudou go">Export Excel</a><br/>
        <a href="{% url 'emr:export_excel_full' %}" accesskey="2" class="button is-doudou go">Export Excel Full</a><br/>
        <a href="{% url 'emr:export_data_model' %}" accesskey="2" class="button is-doudou go">Export Data Model</a><br/>
			</div>
		{% endif %}

	</section>
{% endblock %}

emr/templates/emr/patient.html
{% extends "emr/base.html" %}

{% block content %}
  <section class="hero is-light">
    <div class="hero-body">
      <br/>
      <div class="container">
        {% with record_id=record.1 table_id=record.0 %}
          <table>
            <tr>
              <td><span class="title">Patient #{{ record.3.0.4 }}</span></td>
              {% if easyUser.tables.1.view_table %}
                <td width="5%"><a href="{% url 'emr:detail' table_id record_id %}" class="button is-mei go">View</a></td>
                <td width="5%"><a href="{% url 'emr:print' table_id record_id %}" class="button is-mei go">Print</a></td>
              {% endif %}
              {% if easyUser.tables.1.edit_table %}
                <td width="5%"><a href="{% url 'emr:edit' table_id record_id %}" class="button is-mei careful">Edit</a></td>
              {% endif %}
              {% if easyUser.tables.1.delete_table %}
                <td width="5%">
                  <a href="{% url 'emr:deleterecord' table_id record_id %}"
                      class="button is-mei dangerous"
                      onclick="return confirm('Are you sure you want to delete this patient?')">
                    Delete
                  </a>
                </td>
              {% endif %}
            </tr>
          </table>
        {% endwith %}
      </div>
      <div class="container">
        <br/>
        <table class="table">
          {% for field in record.3 %}
            <tr>
              <td><b>{% if field.3 == None %}Not recorded{% else %}{{ field.3 }}{% endif %}</b></td>
              <td>{% if field.4 == None %}Not recorded{% else %}{{ field.4 }}{% endif %}</td>
            </tr>
          {% endfor %}
        </table>
      </div>
      {% if relatedrecords %}
        <br/>
        {% for relatedrecord in relatedrecords %}
          {% for tableresults in relatedrecord.1 %}
            {% with table_id=tableresults.1 table_id2=tableresults.1 related_record_entry=relatedrecord.0.0 %}
              <div class="container">
                <table>
                  <tr>
                    <td><span class="subtitle">{{ tableresults.0 }}</span></td>
                    {% for k,v in easyUser.tables.items %}
                      {% if k == table_id and v.add_table %}
                        <td width='5%'>
                          <a href="{% url 'emr:addrecord' table_id related_record_entry %}" class="button is-mei go">
                            Add
                          </a>
                        </td>
                      {% endif %}
                    {% endfor %}
                  </tr>
                </table>
              </div>
            {% endwith %}
            <div class="container">
              <div class="columns">
                <div class="column is-12 scroll">
                  <table id="nofeatures" class="table is-striped is-bordered" cellspacing="0" width="100%">
                    <thead>
                      <tr>
                        {% for k,v in easyUser.tables.items %}
                          {% if k == tableresults.1 and v.view_table %}
                            <th  scope="col" width="5%">View</td>
                          {% endif %}
                        {% endfor %}
                        {% for columnname in tableresults.2 %}
                          <th scope="col">{{ columnname }}</td>
                        {% endfor %}
                        {% for k,v in easyUser.tables.items %}
                          {% if k == tableresults.1 and v.edit_table %}
                            <th  scope="col" width="5%">Edit</td>
                          {% endif %}
                        {% endfor %}
                        {% for k,v in easyUser.tables.items %}
                          {% if k == tableresults.1 and v.delete_table %}
                            <th  scope="col" width="5%">Delete</td>
                          {% endif %}
                        {% endfor %}
                      </tr>
                    </thead>
                    <tbody>
                      {% if not tableresults.3 %}
                        <tr>
                          <td colspan="{{ tableresults.2|length|add:'+3' }}">No related records found</td>
                        </tr>
                      {% else %}
                        {% for records in tableresults.3 %}
                          <tr>
                            {% with record_id=records.0 table_id=tableresults.1 %}
                              {% for k,v in easyUser.tables.items %}
                                {% if k == tableresults.1 and v.view_table %}
                                  <td width="5%"><a href="{% url 'emr:detail' table_id record_id %}" class="button is-mei go">View</a></td>
                                {% endif %}
                              {% endfor %}
                            {% endwith %}
                            {% for record in records %}
                              {% if forloop.counter != 1 %}
                                {% with record_id=records.0 table_id=tableresults.1 %}
                                  <td>{% if record == None %}Not recorded{% else %}{{ record }}{% endif %}</td>
                                {% endwith %}
                              {% endif %}
                            {% endfor %}
                            {% with record_id=records.0 table_id=tableresults.1 %}
                              {% for k,v in easyUser.tables.items %}
                                {% if k == tableresults.1 and v.edit_table %}
                                  <td width="5%"><a href="{% url 'emr:edit' table_id record_id %}" class="button is-mei careful">Edit</a></td>
                                {% endif %}
                              {% endfor %}
                              {% for k,v in easyUser.tables.items %}
                                {% if k == tableresults.1 and v.delete_table %}
                                  <td width="5%">
                                    <a href="{% url 'emr:deleterecord' table_id record_id %}"
                                        class='button is-mei dangerous'
                                        onclick="return confirm('Are you sure you want to delete this record?')">
                                      Delete
                                    </a>
                                  </td>
                                {% endif %}
                              {% endfor %}
                            {% endwith %}
                          </tr>
                        {% endfor %}
                        {% for chart in charts %}
                          {% if chart.0 == tableresults.1 %}
                          <tr>
                            <td colspan="{{ tableresults.2|length|add:'+3' }}">
                              <center>
                                <br/>
                                <strong>{{ chart.1.options.title }} diagram</strong><br/>
                                {{ chart.1.as_html }}
                              </center>
                            </td>
                          </tr>
                          {% endif %}
                        {% endfor %}
                      {% endif %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          {% endfor %}
          <p><br/></p>
        {% endfor %}
      {% endif %}
    </div>
    <br/>
  </section>
{% endblock content %}

emr/templates/emr/results.html
{% extends "emr/base.html" %}

{% block content %}
  <section class="hero doudoucolor">
    <div align="center">
      <br/>
      <form action="{% url 'emr:results' %}" type="get">
        <table>
          <tr><input type="text" id="searchstring" placeholder="Access by ID or search patients" name="searchstring" class="searchbox" /></tr>
          <tr>&nbsp;</tr>
          <tr><b>&</b></tr>
          <tr>&nbsp;</tr>
          <tr><input type="submit" name="search" value="SEARCH" class="searchnow" /></tr>
        </table>
      </form>
    </div>
  </section>
  <section class="hero is-light">
    <div class="hero-body">
      <br/>
      <div class="container">
        <h1 class="title">Patient(s) matching "{{ searchresults.0.0 }}":</h1>
      </div>
    </div>
    <div class="container">
      <div class="columns">
        {% for tableresults in searchresults.1 %}
          <div class="column is-12 scroll">
            <table id="nofeatures" class="table is-striped is-bordered" cellspacing="0" width="100%">
              <thead>
                <tr>
                  {% for columnname in tableresults.2 %}
                    <th scope="col">{{ columnname }}</td>
                  {% endfor %}
                  {% if easyUser.tables.1.view_table %}
                    <th scope="col" width="5%">View</td>
                    <th scope="col" width="5%">Print</td>
                  {% endif %}
                  {% if easyUser.tables.1.edit_table %}<th scope="col" width="5%">Edit</td>{% endif %}
                  {% if easyUser.tables.1.delete_table %}<th scope="col" width="5%">Delete</td>{% endif %}
                </tr>
              </thead>
              <tbody>
                {% if not tableresults.3 %}
                  <tr>
                    <td colspan="{{ tableresults.2|length|add:'+2' }}">No results found for this search</td>
                  </tr>
                {% else %}
                  {% for records in tableresults.3 %}
                    <tr>
                      {% for record in records %}
                        {% if forloop.counter == 2 %}
                          {% with record_id=records.0 %}
                            <td><a href="{% url 'emr:patient' record_id %}" class="button is-mei go">{{ record }}</a></td>
                          {% endwith %}
                        {% elif forloop.counter != 1 %}
                          {% with record_id=records.0 %}
                            <td>{% if record == None %}Not recorded{% else %}{{ record }}{% endif %}</td>
                          {% endwith %}
                        {% endif %}
                      {% endfor %}
                      {% with record_id=records.0 table_id=tableresults.1 %}
                        {% if easyUser.tables.1.view_table %}
                          <td width="5%"><a href="{% url 'emr:detail' table_id record_id %}" class="button is-mei go">View</a></td>
                          <td width="5%"><a href="{% url 'emr:print' table_id record_id %}" class="button is-mei go">Print</a></td>
                        {% endif %}
                        {% if easyUser.tables.1.edit_table %}
                          <td width="5%"><a href="{% url 'emr:edit' table_id record_id %}" class="button is-mei careful">Edit</a></td>
                        {% endif %}
                        {% if easyUser.tables.1.delete_table %}
                          <td width="5%">
                            <a href="{% url 'emr:deleterecord' table_id record_id %}"
                                class="button is-mei dangerous"
                                onclick="return confirm('Are you sure you want to delete this record?')">
                              Delete
                            </a>
                          </td>
                        {% endif %}
                      {% endwith %}
                    </tr>
                  {% endfor %}
                {% endif %}
              </tbody>
            </table>
          </div>
        {% endfor %}
      </div>
      <p></p>
      <i>* This version of EasyNut is limited to 100 results per table. If you reached this limit and did not find anything relevant, refine your search</i>
      <p><br/></p>
    </div>
  </section>
{% endblock content %}