builder/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views


app_name = "builder"

urlpatterns = [
    url(r"^$", views.home, name="home"),
    url(r"^add/$", views.model_add, name="model_add"),
    url(r"^(?P<model_id>[0-9]+)/$", views.model_view, name="model_view"),
    url(r"^(?P<model_id>[0-9]+)/edit/$", views.model_edit, name="model_edit"),
]

builder/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from emr.models import DynamicRegistry


@login_required
def home(request):
    """Builder home page."""
    DynamicRegistry.init()
    context = {
        "models_config": DynamicRegistry.models_config.values(),
    }
    return render(request, "builder/home.html", context)


@login_required
def model_add(request):
    """Create a new model."""
    context = {}
    return render(request, "builder/model_add.html", context)


@login_required
def model_view(request, model_id):
    """View detailed information about the given model."""
    context = {
        "model_id": model_id,
    }
    return render(request, "builder/model_view.html", context)


@login_required
def model_edit(request, model_id):
    """Modify the given model."""
    context = {
        "model_id": model_id,
    }
    return render(request, "builder/model_edit.html", context)

builder/templates/builder/base.html
{% extends "emr/base.html" %}

{% block content %}
  <section class="hero is-light">
    <div class="hero-body">
      <br/>
      <div class="container">
        <h1 class="title">Builder</h1>

        {% block builder_content %}{% endblock builder_content %}
      </div>
    </div>
    <br/>
  </section>
{% endblock content %}

builder/templates/builder/home.html
{% extends "builder/base.html" %}

{% block builder_content %}
  <div class="columns">
    <div class="column is-12 scroll">
      <table>
        <tr>
          <td><span class="subtitle">Models</span></td>
          <td width="5%"><a href="{% url 'builder:model_add' %}" class="button is-mei go">Add</a></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="columns">
    <div class="column is-12 scroll">
      <table class="table is-striped is-bordered">
        <thead>
          <tr>
            <th class="nowrap" width="5%">Model ID</th>
            <th>Name</th>
            <th class="nowrap" colspan="2" width="5%">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for model_config in models_config %}
            <tr>
              <td>{{ model_config.id }}</td>
              <td>{{ model_config.name }}</td>
              <td><a href="{% url 'builder:model_view' model_config.id %}" class="button is-mei go">View</a></td>
              <td><a href="{% url 'builder:model_edit' model_config.id %}" class="button is-mei careful">Edit</a></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock builder_content %}

builder/templates/builder/model_add.html
{% extends "builder/base.html" %}

{% block builder_content %}
  <div class="columns">
    <div class="column is-12 scroll">
      <table>
        <tr>
          <td><span class="subtitle">Create new Model</span></td>
          <td width="5%"><a href="javascript:history.back()" class="button is-mei careful" onclick="return confirm('The changes made are not going to be saved. Are you sure?')">Back</a></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="columns">
    <div class="column is-12 scroll">
    </div>
  </div>
{% endblock builder_content %}

builder/templates/builder/model_edit.html
{% extends "builder/base.html" %}

{% block builder_content %}
  <div class="columns">
    <div class="column is-12 scroll">
      <table>
        <tr>
          <td><span class="subtitle">Edit Model #{{ model_id }}</span></td>
          <td width="5%"><a href="{% url "builder:model_view" model_id %}" class="button is-mei go">View</a></td>
          <td width="5%"><a href="{% url "builder:home" %}" class="button is-mei go">List</a></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="columns">
    <div class="column is-12 scroll">
    </div>
  </div>
{% endblock builder_content %}

builder/templates/builder/model_view.html
{% extends "builder/base.html" %}

{% block builder_content %}
  <div class="columns">
    <div class="column is-12 scroll">
      <table>
        <tr>
          <td><span class="subtitle">View Model #{{ model_id }}</span></td>
          <td width="5%"><a href="{% url "builder:model_edit" model_id %}" class="button is-mei careful">Edit</a></td>
          <td width="5%"><a href="{% url "builder:home" %}" class="button is-mei go">List</a></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="columns">
    <div class="column is-12 scroll">
    </div>
  </div>
{% endblock builder_content %}